import Foundation

/// Manages the Claude Code `PreToolUse` hook that pairs with
/// `PermissionServer`. Idempotent install / uninstall: we read the
/// user's `~/.claude/settings.json`, find or remove our own block by
/// matching on the script path, and rewrite the file atomically.
///
/// We never touch any other entries in `hooks.PreToolUse`, so users can
/// keep their own custom hooks alongside Rover's.
enum PermissionHookInstaller {
    static let scriptDir: String = {
        let home = NSString("~/.claude/rover-hooks").expandingTildeInPath
        return home
    }()
    static let scriptPath = "\(scriptDir)/pretooluse.sh"
    static let portFile = "\(scriptDir)/.port"
    static let settingsPath = NSString("~/.claude/settings.json").expandingTildeInPath

    private static let scriptContents = #"""
#!/usr/bin/env bash
# Auto-generated by Rover.app. Do not edit by hand — re-installed on
# every Rover launch when "Permission Bubble" is enabled.
#
# Reads a Claude Code PreToolUse JSON event from stdin, POSTs it to
# Rover's local server, and prints Rover's decision JSON to stdout
# (which Claude Code interprets as the hook's permission decision).
#
# Failure modes (Rover not running, server unreachable, etc.) all exit
# 0 with no stdout — Claude Code then falls back to its built-in
# permission prompt, so the agent never gets stuck.
PORT_FILE="$HOME/.claude/rover-hooks/.port"
[[ -f "$PORT_FILE" ]] || exit 0
PORT=$(cat "$PORT_FILE" 2>/dev/null)
[[ -n "$PORT" ]] || exit 0

RESPONSE=$(cat | curl -sS \
    --connect-timeout 1 \
    --max-time 600 \
    -H 'Content-Type: application/json' \
    --data-binary @- \
    "http://127.0.0.1:$PORT/pretooluse" 2>/dev/null) || exit 0

[[ -n "$RESPONSE" ]] && echo "$RESPONSE"
exit 0
"""#

    /// Write the script (idempotent), make it executable, and ensure
    /// `~/.claude/settings.json` references it under
    /// `hooks.PreToolUse`. Throws on filesystem / JSON errors.
    static func install() throws {
        let fm = FileManager.default
        try fm.createDirectory(atPath: scriptDir, withIntermediateDirectories: true)
        try scriptContents.write(toFile: scriptPath, atomically: true, encoding: .utf8)
        try fm.setAttributes([.posixPermissions: NSNumber(value: Int16(0o755))],
                             ofItemAtPath: scriptPath)
        try ensureSettingsEntry()
    }

    /// Remove our block from `~/.claude/settings.json` and delete the
    /// hook directory. Best-effort — silently ignores files that aren't
    /// there.
    static func uninstall() {
        try? removeSettingsEntry()
        let fm = FileManager.default
        try? fm.removeItem(atPath: scriptPath)
        try? fm.removeItem(atPath: portFile)
        // Leave the directory alone if anyone else has dropped files in
        // it (unlikely, but cheap politeness).
        if let contents = try? fm.contentsOfDirectory(atPath: scriptDir),
           contents.isEmpty {
            try? fm.removeItem(atPath: scriptDir)
        }
    }

    /// Write the current TCP port the hook script should connect to.
    /// Called every time the server (re)starts.
    static func writePort(_ port: UInt16) throws {
        try FileManager.default.createDirectory(
            atPath: scriptDir, withIntermediateDirectories: true)
        try "\(port)\n".write(toFile: portFile, atomically: true, encoding: .utf8)
    }

    static func clearPort() {
        try? FileManager.default.removeItem(atPath: portFile)
    }

    // MARK: - settings.json surgery

    private static func ensureSettingsEntry() throws {
        var root: [String: Any] = [:]
        let url = URL(fileURLWithPath: settingsPath)
        if let data = try? Data(contentsOf: url),
           let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            root = parsed
        }

        var hooks = root["hooks"] as? [String: Any] ?? [:]
        var preList = hooks["PreToolUse"] as? [[String: Any]] ?? []
        // Drop any prior entry pointing at our script so we don't grow
        // duplicates across launches.
        preList.removeAll { block in
            blockReferencesOurScript(block)
        }
        // Insert ours at the front: we want the first say so users can
        // veto a tool call before any other hook (e.g. a logger) runs.
        let block: [String: Any] = [
            "hooks": [
                ["type": "command", "command": scriptPath]
            ]
        ]
        preList.insert(block, at: 0)
        hooks["PreToolUse"] = preList
        root["hooks"] = hooks

        let out = try JSONSerialization.data(
            withJSONObject: root,
            options: [.prettyPrinted, .sortedKeys])
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true)
        try out.write(to: url, options: .atomic)
    }

    private static func removeSettingsEntry() throws {
        let url = URL(fileURLWithPath: settingsPath)
        guard let data = try? Data(contentsOf: url),
              var root = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return }
        guard var hooks = root["hooks"] as? [String: Any],
              var preList = hooks["PreToolUse"] as? [[String: Any]] else { return }
        let before = preList.count
        preList.removeAll { blockReferencesOurScript($0) }
        guard preList.count != before else { return }
        if preList.isEmpty {
            hooks.removeValue(forKey: "PreToolUse")
        } else {
            hooks["PreToolUse"] = preList
        }
        if hooks.isEmpty {
            root.removeValue(forKey: "hooks")
        } else {
            root["hooks"] = hooks
        }
        let out = try JSONSerialization.data(
            withJSONObject: root,
            options: [.prettyPrinted, .sortedKeys])
        try out.write(to: url, options: .atomic)
    }

    private static func blockReferencesOurScript(_ block: [String: Any]) -> Bool {
        guard let inner = block["hooks"] as? [[String: Any]] else { return false }
        return inner.contains { ($0["command"] as? String) == scriptPath }
    }
}
