import Foundation

/// Cursor Agent supports user-level hooks at `~/.cursor/hooks.json`.
/// We register `beforeShellExecution` and `beforeReadFile` to forward
/// notifications to Rover's `/observe` endpoint, so the dog plays the
/// matching animation when Cursor is the active agent in another
/// terminal.
///
/// Idempotent: install / uninstall always re-finds our entries by
/// command path and leaves anything else alone.
enum CursorHookInstaller {
    static let scriptDir = NSString("~/.cursor/rover-hooks").expandingTildeInPath
    static let shellScript = "\(scriptDir)/before-shell.sh"
    static let readScript = "\(scriptDir)/before-read.sh"
    static let portFile = NSString("~/.claude/rover-hooks/.port").expandingTildeInPath
    static let settingsPath = NSString("~/.cursor/hooks.json").expandingTildeInPath

    /// One-way fire-and-forget shell script. Cursor's native stdin JSON
    /// is forwarded verbatim — the server reads the agent + kind from
    /// the URL query string and digs the summary out of the body's
    /// command / file_path / path fields itself.
    private static func script(kind: String) -> String {
        return """
        #!/usr/bin/env bash
        # Auto-generated by Rover.app — re-installed on every launch when
        # "Cursor observer" is enabled. Forwards a one-way notification of
        # the hook event to Rover; Cursor's agent is never blocked.
        PORT_FILE="$HOME/.claude/rover-hooks/.port"
        [[ -f "$PORT_FILE" ]] || exit 0
        PORT=$(cat "$PORT_FILE" 2>/dev/null)
        [[ -n "$PORT" ]] || exit 0

        # Forward Cursor's stdin JSON verbatim. Short max-time so a slow
        # Rover never stalls Cursor.
        cat | curl -s --connect-timeout 1 --max-time 2 \\
            -H 'Content-Type: application/json' \\
            --data-binary @- \\
            "http://127.0.0.1:$PORT/observe?agent=cursor&kind=\(kind)" \\
            >/dev/null 2>&1 || true
        exit 0
        """
    }

    static func install() throws {
        let fm = FileManager.default
        try fm.createDirectory(atPath: scriptDir, withIntermediateDirectories: true)

        try script(kind: "toolCall").write(toFile: shellScript, atomically: true, encoding: .utf8)
        try script(kind: "readFile").write(toFile: readScript, atomically: true, encoding: .utf8)
        let perms: [FileAttributeKey: Any] = [.posixPermissions: NSNumber(value: Int16(0o755))]
        try fm.setAttributes(perms, ofItemAtPath: shellScript)
        try fm.setAttributes(perms, ofItemAtPath: readScript)

        try ensureSettingsEntry()
    }

    static func uninstall() {
        try? removeSettingsEntry()
        let fm = FileManager.default
        try? fm.removeItem(atPath: shellScript)
        try? fm.removeItem(atPath: readScript)
        if let contents = try? fm.contentsOfDirectory(atPath: scriptDir),
           contents.isEmpty {
            try? fm.removeItem(atPath: scriptDir)
        }
    }

    // MARK: - hooks.json surgery

    private static func ensureSettingsEntry() throws {
        var root: [String: Any] = ["version": 1]
        let url = URL(fileURLWithPath: settingsPath)
        if let data = try? Data(contentsOf: url),
           let parsed = try? JSONSerialization.jsonObject(with: data) as? [String: Any] {
            root = parsed
            // Cursor pins schema version 1.
            if root["version"] == nil { root["version"] = 1 }
        }
        var hooks = root["hooks"] as? [String: Any] ?? [:]

        register(into: &hooks, key: "beforeShellExecution", scriptPath: shellScript)
        register(into: &hooks, key: "beforeReadFile", scriptPath: readScript)

        root["hooks"] = hooks
        let out = try JSONSerialization.data(
            withJSONObject: root,
            options: [.prettyPrinted, .sortedKeys])
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true)
        try out.write(to: url, options: .atomic)
    }

    private static func register(into hooks: inout [String: Any],
                                 key: String,
                                 scriptPath: String) {
        var list = hooks[key] as? [[String: Any]] ?? []
        list.removeAll { ($0["command"] as? String) == scriptPath }
        list.insert(["command": scriptPath], at: 0)
        hooks[key] = list
    }

    private static func removeSettingsEntry() throws {
        let url = URL(fileURLWithPath: settingsPath)
        guard let data = try? Data(contentsOf: url),
              var root = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        else { return }
        guard var hooks = root["hooks"] as? [String: Any] else { return }
        for key in ["beforeShellExecution", "beforeReadFile"] {
            guard var list = hooks[key] as? [[String: Any]] else { continue }
            list.removeAll {
                let cmd = $0["command"] as? String
                return cmd == shellScript || cmd == readScript
            }
            if list.isEmpty {
                hooks.removeValue(forKey: key)
            } else {
                hooks[key] = list
            }
        }
        if hooks.isEmpty {
            root.removeValue(forKey: "hooks")
        } else {
            root["hooks"] = hooks
        }
        let out = try JSONSerialization.data(
            withJSONObject: root,
            options: [.prettyPrinted, .sortedKeys])
        try out.write(to: url, options: .atomic)
    }
}
